export const provenContractsAbi = [
  {
    type: "function",
    name: "createContract",
    stateMutability: "nonpayable",
    inputs: [
      { name: "buyer", type: "address" },
      { name: "seller", type: "address" },
      { name: "value", type: "uint256" },
      { name: "currency", type: "bytes32" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ name: "contractId", type: "uint256" }],
  },
  {
    type: "function",
    name: "addCondition",
    stateMutability: "nonpayable",
    inputs: [
      { name: "contractId", type: "uint256" },
      { name: "conditionType", type: "bytes32" },
      { name: "metadataHash", type: "bytes32" },
    ],
    outputs: [{ name: "conditionId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getContract",
    stateMutability: "view",
    inputs: [{ name: "contractId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "buyer", type: "address" },
      { name: "seller", type: "address" },
      { name: "value", type: "uint256" },
      { name: "currency", type: "bytes32" },
      { name: "metadataHash", type: "bytes32" },
      { name: "state", type: "uint8" },
      { name: "createdAt", type: "uint64" },
      { name: "updatedAt", type: "uint64" },
      { name: "conditionCount", type: "uint256" },
      { name: "verifiedConditionCount", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "getCondition",
    stateMutability: "view",
    inputs: [{ name: "conditionId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "contractId", type: "uint256" },
      { name: "conditionType", type: "bytes32" },
      { name: "status", type: "uint8" },
      { name: "metadataHash", type: "bytes32" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "evidenceIssuer", type: "address" },
      { name: "evidenceTimestamp", type: "uint64" },
      { name: "attestationId", type: "bytes32" },
      { name: "verifiedBy", type: "address" },
      { name: "verifiedAt", type: "uint64" },
      { name: "evidenceSubmitted", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "getContractConditionIds",
    stateMutability: "view",
    inputs: [{ name: "contractId", type: "uint256" }],
    outputs: [{ name: "conditionIds", type: "uint256[]" }],
  },
  {
    type: "event",
    name: "ContractCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "contractId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: false, name: "seller", type: "address" },
      { indexed: false, name: "value", type: "uint256" },
      { indexed: false, name: "currency", type: "bytes32" },
      { indexed: false, name: "metadataHash", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "ConditionAdded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "contractId", type: "uint256" },
      { indexed: true, name: "conditionId", type: "uint256" },
      { indexed: false, name: "conditionType", type: "bytes32" },
      { indexed: false, name: "metadataHash", type: "bytes32" },
    ],
  },
] as const;
